pipeline:
  test:
    image: clojure:lein-alpine

    commands:
      - lein eastwood
      - lein kibit
      - lein test
services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=coffeetable
      - POSTGRES_PASSWORD=coffeetable
